name: CodeGuru Review Workflow

on:
  push:
    branches:
      - main

jobs:
  codeguru-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::220904045354:role/my-github-actions-role
          aws-region: us-east-1

      - name: CodeGuru Reviewer
        uses: aws-actions/codeguru-reviewer@v1.1
        with:
          build_path: target # build artifact(s) directory
          s3_bucket: codeguru-reviewer-test123  # S3 Bucket with "codeguru-reviewer-*" prefix

      - name: Upload review result
        if: ${{ github.event_name != 'push' }}
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: codeguru-results.sarif.json
