name: CodeGuru Review Workflow

on:
  push:
    branches:
      - main

jobs:
  codeguru-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure AWS credentials
        id: iam-role
        continue-on-error: true
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
          role-session-name: GitHub-Action-Role
          aws-region: ${{ env.AWS_REGION }}

      - name: CodeGuru Reviewer
        uses: aws-actions/codeguru-reviewer@v1.1
        with:
          # build_path: CodeGuruSecurity # build artifact(s) directory
          s3_bucket: codeguru-reviewer-target  # S3 Bucket with "codeguru-reviewer-*" prefix

      - name: Debug Info
        run: |
          ls -R   # List files in the current directory and subdirectories
          cat codeguru-results.sarif.json   # Output the contents of the SARIF file

      - name: Store SARIF file
        if: steps.iam-role.outcome == 'success'
        uses: actions/upload-artifact@v2
        with:
          name: SARIF_recommendations
          path: ./codeguru-results.sarif.json

      - name: Upload review result
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: codeguru-results.sarif.json
